openapi: 3.0.1
info:
  title: example
  version: ''
paths:
  /example/application:
    get:
      operationId: example_ReadAllApplication
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name,note
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/Application'
              examples:
                Example1:
                  value:
                    d:
                      - id: 4667
                        name: asazpqprbwfzcgqpwggq
                        note: eqydvcitnsirwajnugcd
                      - id: 4667
                        name: asazpqprbwfzcgqpwggq
                        note: eqydvcitnsirwajnugcd
    patch:
      operationId: example_UpdateAllApplication
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name,note
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteAllApplication
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name,note
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
  /example/application(id):
    get:
      operationId: example_ReadApplication
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
              examples:
                Example1:
                  value:
                    id: 4667
                    name: asazpqprbwfzcgqpwggq
                    note: eqydvcitnsirwajnugcd
    post:
      operationId: example_CreateApplication
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
              examples:
                Example1:
                  value:
                    id: 4667
                    name: asazpqprbwfzcgqpwggq
                    note: eqydvcitnsirwajnugcd
    patch:
      operationId: example_UpdateApplication
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteApplication
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
  /example/device:
    get:
      operationId: example_ReadAllDevice
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name,type,belongs_to__application
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/Device'
              examples:
                Example1:
                  value:
                    d:
                      - id: 82776
                        name: kwyepepbhyjahnafvbmz
                        type: duxabktuxrqniguywjzn
                      - id: 82776
                        name: kwyepepbhyjahnafvbmz
                        type: duxabktuxrqniguywjzn
    patch:
      operationId: example_UpdateAllDevice
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name,type,belongs_to__application
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteAllDevice
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name,type,belongs_to__application
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
  /example/device(id):
    get:
      operationId: example_ReadDevice
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
              examples:
                Example1:
                  value:
                    id: 82776
                    name: kwyepepbhyjahnafvbmz
                    type: duxabktuxrqniguywjzn
    post:
      operationId: example_CreateDevice
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
              examples:
                Example1:
                  value:
                    id: 82776
                    name: kwyepepbhyjahnafvbmz
                    type: duxabktuxrqniguywjzn
    patch:
      operationId: example_UpdateDevice
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteDevice
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
  /example/gateway:
    get:
      operationId: example_ReadAllGateway
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/Gateway'
              examples:
                Example1:
                  value:
                    d:
                      - id: 93907
                        name: grwlnjidfweccerzvxgo
                      - id: 93907
                        name: grwlnjidfweccerzvxgo
    patch:
      operationId: example_UpdateAllGateway
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteAllGateway
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,name
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
  /example/gateway(id):
    get:
      operationId: example_ReadGateway
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gateway'
              examples:
                Example1:
                  value:
                    id: 93907
                    name: grwlnjidfweccerzvxgo
    post:
      operationId: example_CreateGateway
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gateway'
              examples:
                Example1:
                  value:
                    id: 93907
                    name: grwlnjidfweccerzvxgo
    patch:
      operationId: example_UpdateGateway
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteGateway
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
  /example/gateway__connects__device:
    get:
      operationId: example_ReadAllGateway__connects__device
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,gateway,connects__device
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/Gateway__connects__device'
              examples:
                Example1:
                  value:
                    d:
                      - id: 58529
                      - id: 58529
    patch:
      operationId: example_UpdateAllGateway__connects__device
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,gateway,connects__device
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteAllGateway__connects__device
      tags:
        - Example
      parameters:
        - name: $filter
          in: query
          required: false
          schema:
            type: string
        - name: $select
          in: query
          required: false
          schema:
            type: string
          examples:
            Example1:
              value: created_at,modified_at,id,gateway,connects__device
        - name: $expand
          in: query
          required: false
          schema:
            type: string
        - name: $top
          in: query
          required: false
          schema:
            type: integer
        - name: $count
          in: query
          required: false
          schema:
            type: integer
      responses:
        '204':
          description: ''
  /example/gateway__connects__device(id):
    get:
      operationId: example_ReadGateway__connects__device
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gateway__connects__device'
              examples:
                Example1:
                  value:
                    id: 58529
    post:
      operationId: example_CreateGateway__connects__device
      tags:
        - Example
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gateway__connects__device'
              examples:
                Example1:
                  value:
                    id: 58529
    patch:
      operationId: example_UpdateGateway__connects__device
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
    delete:
      operationId: example_DeleteGateway__connects__device
      tags:
        - Example
      parameters: []
      responses:
        '204':
          description: ''
components:
  schemas:
    Application:
      title: Application
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
          description: The unique identifier for a Application
          example: 4667
        name:
          type: string
          example: asazpqprbwfzcgqpwggq
        note:
          type: string
          example: eqydvcitnsirwajnugcd
      required:
        - id
        - name
        - note
    Device:
      title: Device
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
          description: The unique identifier for a Device
          example: 82776
        name:
          type: string
          example: kwyepepbhyjahnafvbmz
        type:
          type: string
        belongs_to__application:
          $ref: '#/components/schemas/Application'
      required:
        - id
        - name
    Gateway:
      title: Gateway
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
          description: The unique identifier for a Gateway
          example: 93907
        name:
          type: string
      required:
        - id
    Gateway__connects__device:
      title: Gateway__connects__device
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time
        id:
          type: integer
          format: int64
          description: The unique identifier for a Gateway__connects__device
          example: 58529
        gateway:
          $ref: '#/components/schemas/Gateway'
        connects__device:
          $ref: '#/components/schemas/Device'
      required:
        - id
  securitySchemes: {}
